Задание 1.2.1

In [ ]:
import numpy as np

x = np.array([[1,2], [3,4], [5,6], [7,8], [9,10]])
print(x)
print(x[3][1])
print(x[1])

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
7
[2 3]


Задание 1.2.2

In [ ]:
import numpy as np

a = np.zeros(10)
b = np.ones(10)
c = np.full(10,5)
d = np.arange(10,20)
print(a, "\n", b, "\n", c, "\n", d)


Задание 1.2.3

In [ ]:
import numpy as np

z = np.random.random((10,10))
Zmin, Zmax, Zmean = z.min(), z.max(), z.mean()
print(Zmin, Zmax, Zmean)

0.01277791675000095 0.9950647944391594 0.4446672171999513


Задание 1.2.4

In [ ]:
import numpy as np

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Задание 1.2.5

In [ ]:
import numpy as np

print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

Задание 1.2.6

In [ ]:
import numpy as np

arr = np.array([2,1,5,3,7,4,6,8])
print(np.sort(arr))

Задание 1.3.1

In [ ]:
import numpy as np


arr = np.empty((8,8))
for i in range(8):
  for j in range(8):
    if i % 2 == 0:
      if j % 2 == 0:
        arr[i][j] = 1
      else:
        arr[i][j] = 0
    else:
      if j % 2 != 0:
        arr[i][j] = 1
      else:
        arr[i][j] = 0
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


Задание 1.3.2

In [ ]:
import numpy as np

arr = np.empty((5,5))
for i in range(5):
  arr[i] = np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Задание 1.3.3

In [ ]:
import numpy as np

arr = np.random.sample((3,3,3))
print(arr)





Задание 1.3.4

In [ ]:
import numpy as np

arr = np.ones((3,3))
arr[1][1] = 0
print(arr)

Задание 1.3.5

In [ ]:
import numpy as np

arr = np.arange(10)
print(arr)
arr = np.sort(arr)[::-1]
print(arr)


Задание 1.3.6

In [ ]:
arr = np.arange(10).reshape((2,5))
print(arr)
print(np.ndim(arr))
print(np.shape(arr))
print(np.size(arr))

Задание 2.2.1

In [ ]:
import pandas as pd
import numpy as np

lst = [1, 2, 3, 4, 5]
d = {"a": 1, "b" : 2, "c" : 3}
ndarr = np.array([1,2,3,4,5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr)

print(s1)
print(s2)
print(s3)

Задание 2.2.2

In [ ]:
import pandas as pd

s1 = pd.Series([1,2,3,4,5], ["a", "b", "c", "d", "e"])
s2 = pd.Series([5,4,3,2,1])

print(s1["a"])
print(s2[0])
print(s2[3:])

Задание 2.2.3

In [ ]:
import pandas as pd

dataframe = pd.DataFrame()
dataframe["Имя"] = ["Джеки Джексон", "Стивен Стивенсон"]
dataframe["Возраст"] = [38,25]
dataframe["Водитель"] = [True, False]
print(dataframe)

                Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False


Задание 2.2.4

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv"
dataframe = pd.read_csv(url)
dataframe.head(5)


Задание 2.2.5

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv"
dataframe = pd.read_csv(url)
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()


Задание 2.2.6

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv"
dataframe = pd.read_csv(url)
dataframe.iloc[1:4]

Задание 2.2.7

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv"
dataframe = pd.read_csv(url)
dataframe[dataframe["PClass"] == "1st"].head(2)


Задание 2.3.1

In [ ]:
import pandas as pd
import math as m

def Evkdlid_len(s1,s2):
    res = 0
    for i in range(len(s1)):
      res += m.sqrt(s1[i]**2+s2[i]**2)
    return res

s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([6,7,8,9,10])
print(Evkdlid_len(s1,s2))

Задание 2.3.2

In [ ]:
import pandas as pd

dataframe = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/main/kobe.csv")
dataframe



Задание 2.3.3

In [ ]:
import pandas as pd

dataframe = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/main/kobe.csv")

dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

dataframe.iloc[1:4]

dataframe[dataframe["game"] == 1].head(2)

Задание 3.2.1

In [ ]:
import numpy as np
from sklearn import preprocessing

feature = np.array([-500.5], [-100.1], [0], [100.1], [900.9])
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0,1))
scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature

Задание 3.2.2

In [ ]:
import numpy as np
from sklearn import preprocessing

x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
print(standardized)

print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

Задание 3.3.1

In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                  'B':[103.02,107.26,110.35,114.23,114.68],
                  'C':['big','small','big','small','small']})

dfTest[["A", "B"]] = scaler.fit_transform(dfTest[["A", "B"]])
dfTest

Задание 3.3.2

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

dataframe = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/master/iris.csv")
scalerX = MinMaxScaler()
scalerZ = StandardScaler()
dataframe[["sepal_length_cm"]] = scalerZ.fit_transform(dataframe[["sepal_length_cm"]])
dataframe
dataframe[["petal_width_cm"]] = scalerX.fit_transform(dataframe[["petal_width_cm"]])
dataframe